# Generated by Django 5.1.6 on 2025-03-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeteriamenu',
            name='is_preorder_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafeteriamenu',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], default='Breakfast', max_length=20),
        ),
    ]
